# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 220)
        Form.setMinimumSize(QtCore.QSize(600, 220))
        Form.setMaximumSize(QtCore.QSize(600, 220))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/logo_wk.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.groupBox_setting = QtWidgets.QGroupBox(Form)
        self.groupBox_setting.setGeometry(QtCore.QRect(10, 10, 581, 101))
        self.groupBox_setting.setStyleSheet("font: 10pt \"Microsoft YaHei UI\";")
        self.groupBox_setting.setObjectName("groupBox_setting")
        self.label = QtWidgets.QLabel(self.groupBox_setting)
        self.label.setGeometry(QtCore.QRect(10, 30, 41, 21))
        self.label.setObjectName("label")
        self.lineEdit_key = QtWidgets.QLineEdit(self.groupBox_setting)
        self.lineEdit_key.setGeometry(QtCore.QRect(70, 30, 281, 21))
        self.lineEdit_key.setObjectName("lineEdit_key")
        self.label_2 = QtWidgets.QLabel(self.groupBox_setting)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 61, 21))
        self.label_2.setObjectName("label_2")
        self.lineEdit_appid = QtWidgets.QLineEdit(self.groupBox_setting)
        self.lineEdit_appid.setGeometry(QtCore.QRect(70, 60, 281, 21))
        self.lineEdit_appid.setObjectName("lineEdit_appid")
        self.pushButton_confirm_api = QtWidgets.QPushButton(self.groupBox_setting)
        self.pushButton_confirm_api.setGeometry(QtCore.QRect(380, 60, 61, 21))
        self.pushButton_confirm_api.setObjectName("pushButton_confirm_api")
        self.pushButton_clear = QtWidgets.QPushButton(self.groupBox_setting)
        self.pushButton_clear.setGeometry(QtCore.QRect(450, 60, 61, 21))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 130, 581, 71))
        self.groupBox.setStyleSheet("font: 10pt \"Microsoft YaHei UI\";")
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_translate_data_pos = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_translate_data_pos.setGeometry(QtCore.QRect(60, 30, 361, 21))
        self.lineEdit_translate_data_pos.setObjectName("lineEdit_translate_data_pos")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 41, 21))
        self.label_3.setObjectName("label_3")
        self.pushButton_confirm_pos = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_confirm_pos.setGeometry(QtCore.QRect(440, 30, 61, 21))
        self.pushButton_confirm_pos.setObjectName("pushButton_confirm_pos")
        self.pushButton_pos_reset = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_pos_reset.setGeometry(QtCore.QRect(510, 30, 61, 21))
        self.pushButton_pos_reset.setObjectName("pushButton_pos_reset")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "设置"))
        self.groupBox_setting.setTitle(_translate("Form", "百度翻译api"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt;\">Key：</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt;\">AppId：</span></p></body></html>"))
        self.pushButton_confirm_api.setText(_translate("Form", "确认"))
        self.pushButton_clear.setText(_translate("Form", "清空"))
        self.groupBox.setTitle(_translate("Form", "缓存文件"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt;\">位置：</span></p></body></html>"))
        self.pushButton_confirm_pos.setText(_translate("Form", "确认"))
        self.pushButton_pos_reset.setText(_translate("Form", "重置"))
import icons_rc
